name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from SCM
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This ensures we have the git history
        
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Update version
      run: |
        NEW_VERSION=$(./update_version.sh)
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: |
        docker build . \
        --file Dockerfile \
        --tag ${{ secrets.DOCKER_USERNAME }}/my-app:latest \
        --tag ${{ secrets.DOCKER_USERNAME }}/my-app:${{ env.NEW_VERSION }}
        
    - name: Push changes to GitHub
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add pom.xml
        git commit -m "Bump version to ${{ env.NEW_VERSION }}"
        git push
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ env.NEW_VERSION }}
        
    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.AWS_KEY }}
        
    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@16.171.234.74 << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest