name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from SCM
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        ./update_version.sh
        docker build . \
        --build-arg APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) \
        --file Dockerfile \
        --tag ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Push updated pom.xml to GitHub
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update version in pom.xml"


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no IdentityFile=<(echo ${{ secrets.AWS_KEY }}) ubuntu@16.171.234.74\
        'sudo docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:latest'